pool:
  vmImage: 'vs2017-win2016'
  
variables:
  buildConfiguration: 'Release'

steps:

- task: AzurePowerShell@4
  inputs:
    azureSubscription: $(Global.ServiceConnectionName)
    scriptType: 'inlineScript'
    inline: |
      $name=$env:Global_Name
      $documentDbUrl = "https://$name.documents.azure.com/
      $resource = Get-AzureRmResource `
      -ResourceType "Microsoft.DocumentDb/databaseAccounts" `
      -ResourceGroupName $env:Global_ResourceGroupName `
      -ResourceName $name `
      -ApiVersion 2015-04-08
      $primaryMasterKey = (Invoke-AzureRmResourceAction `
      -Action listKeys `
      -ResourceId $resource.ResourceId `
      -ApiVersion 2015-04-08 `
      -Force).primaryMasterKey
      $settings = @{ Search = @{ ServiceName=""; ApiKey="" }; DocumentDb = @{ Key="$primaryMasterKey";Url="$documentDbUrl";RequestUnits="400" }; TableStorage=@{ConnectionString=""} }
      Write-Host $settings
      $settings | Out-File $env:Build_Repository_LocalPath\Eklee.Azure.Functions.GraphQl.Tests\local.settings.json

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests'
  inputs:
    command: 'test'
    configuration: '$(BuildConfiguration)'
    projects: 'Eklee.Azure.Functions.GraphQl.Tests\Eklee.Azure.Functions.GraphQl.Tests.csproj'
    arguments: '--filter Category=Unit'